/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, organization and role */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticket inbox
         * @description Agents and admins see every ticket of the organization; customers only see the tickets of
         *     their own customer record. Filters combine with AND; repeated values of one filter combine with OR.
         */
        get: operations["listTickets"];
        put?: never;
        /**
         * Create a ticket
         * @description `customerId` and `assigneeId` must belong to the caller's organization (the assignee must be an
         *     admin or agent). Unknown and foreign ids get the same 400 field error, so other organizations'
         *     data is never revealed.
         */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inbox metrics for the whole organization
         * @description Not affected by inbox filters. Days are computed in the organization time zone.
         */
        get: operations["getTicketMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        /** Ticket detail */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change status, priority and/or assignee
         * @description JSON Merge Patch semantics: absent fields are unchanged and `assigneeId: null` unassigns the
         *     ticket. Requires `If-Match` with the current version. A patch that changes nothing returns 200
         *     without a new version or activity entry. Errors are checked in this order: 401, 403, 404, 428,
         *     400, 412.
         */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/tickets/{number}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        /**
         * Conversation of a ticket, oldest first
         * @description Not paginated. Customers only receive `public` messages. The ticket `description` is part of
         *     the ticket, not the first message.
         */
        get: operations["listMessages"];
        put?: never;
        /** Reply to the customer or add an internal note */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{number}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        /** Activity log of a ticket, newest first (not paginated) */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated customer search */
        get: operations["listCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members who can be assigned to tickets (admins and agents), by name */
        get: operations["listAssignees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "admin" | "agent" | "customer";
        /** @enum {string} */
        TicketStatus: "open" | "in_progress" | "waiting" | "resolved";
        /** @enum {string} */
        TicketPriority: "urgent" | "high" | "medium" | "low";
        /** @enum {string} */
        TicketChannel: "email" | "chat" | "phone" | "web";
        /**
         * @description `all`: every ticket. `mine`: assigned to the caller and not resolved. `unassigned`: without
         *     assignee and not resolved. `resolved`: status `resolved`. Combined with the other filters by AND.
         * @default all
         * @enum {string}
         */
        TicketView: "all" | "mine" | "unassigned" | "resolved";
        /** @enum {string} */
        MessageVisibility: "public" | "internal";
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example America/Bogota */
            timeZone: string;
        };
        Me: {
            user: components["schemas"]["Member"];
            organization: components["schemas"]["Organization"];
            role: components["schemas"]["Role"];
            /**
             * Format: uuid
             * @description Customer record of a `customer` member; null for admins and agents.
             */
            customerId: string | null;
        };
        /** @description An admin or agent of the organization. */
        Member: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description A member as shown inside other resources, without contact data. */
        MemberRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Customer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            company: string | null;
        };
        TicketSummary: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            number: number;
            subject: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            channel: components["schemas"]["TicketChannel"];
            customer: components["schemas"]["Customer"];
            assignee: components["schemas"]["MemberRef"] | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last activity, either a field change or a public message.
             */
            updatedAt: string;
        };
        /** @description Ticket detail. Same fields as TicketSummary plus `description` and `version`. */
        Ticket: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            number: number;
            subject: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            channel: components["schemas"]["TicketChannel"];
            customer: components["schemas"]["Customer"];
            assignee: components["schemas"]["MemberRef"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            description: string;
            /** Format: int64 */
            version: number;
        };
        TicketCreate: {
            /** Format: uuid */
            customerId: string;
            subject: string;
            description: string;
            /** @default medium */
            priority?: components["schemas"]["TicketPriority"];
            /** @default web */
            channel?: components["schemas"]["TicketChannel"];
            /** Format: uuid */
            assigneeId?: string | null;
        };
        TicketPatch: {
            status?: components["schemas"]["TicketStatus"];
            priority?: components["schemas"]["TicketPriority"];
            /**
             * Format: uuid
             * @description `null` unassigns the ticket.
             */
            assigneeId?: string | null;
        };
        /** @description An empty page past the last one is valid (200 with no items); `totalPages` is 0 when there are no items. */
        TicketPage: {
            items: components["schemas"]["TicketSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        CustomerPage: {
            items: components["schemas"]["Customer"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        ViewCounts: {
            all: number;
            mine: number;
            unassigned: number;
            resolved: number;
        };
        TicketMetrics: {
            open: number;
            /** @description Tickets created today (organization time zone) that are still open. */
            openedToday: number;
            inProgress: number;
            inProgressAssignedToMe: number;
            /** @description Distinct tickets that entered `resolved` today, from the activity log. */
            resolvedToday: number;
            resolvedYesterday: number;
            /**
             * @description Median minutes, rounded to the nearest integer, from creation to the first public agent
             *     message, over tickets created in the last 168 hours that have one; null when there are none.
             */
            firstResponseMinutes: number | null;
            firstResponseTargetMinutes: number;
            views: components["schemas"]["ViewCounts"];
        };
        MessageAuthor: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "agent" | "customer";
        };
        Message: {
            /** Format: uuid */
            id: string;
            body: string;
            visibility: components["schemas"]["MessageVisibility"];
            author: components["schemas"]["MessageAuthor"];
            /** Format: date-time */
            createdAt: string;
        };
        MessageCreate: {
            body: string;
            visibility: components["schemas"]["MessageVisibility"];
        };
        Activity: components["schemas"]["TicketCreatedActivity"] | components["schemas"]["StatusChangedActivity"] | components["schemas"]["PriorityChangedActivity"] | components["schemas"]["AssigneeChangedActivity"];
        TicketCreatedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "created";
            actor: components["schemas"]["MemberRef"];
            /** Format: date-time */
            createdAt: string;
        };
        StatusChangedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "status_changed";
            actor: components["schemas"]["MemberRef"];
            from: components["schemas"]["TicketStatus"];
            to: components["schemas"]["TicketStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        PriorityChangedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "priority_changed";
            actor: components["schemas"]["MemberRef"];
            from: components["schemas"]["TicketPriority"];
            to: components["schemas"]["TicketPriority"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description `from` and `to` keep the member id and the name at the time of the change; null means unassigned. */
        AssigneeChangedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assignee_changed";
            actor: components["schemas"]["MemberRef"];
            from: components["schemas"]["MemberRef"] | null;
            to: components["schemas"]["MemberRef"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description RFC 9457 Problem Details. An absent `type` means `about:blank`, as the RFC defines. */
        Problem: {
            /** @default about:blank */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Field errors of a validation failure. */
            errors?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Malformed request, invalid parameter or validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No authenticated principal. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The role does not allow the action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found in the caller's scope. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource changed since the client read it. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The update did not send `If-Match`. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The action is not allowed in the current state of the resource (for example archiving twice). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TicketNumber: number;
        /** @description Zero-based page index. */
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: {
        /** @description Current version of the resource, quoted, for `If-Match`. */
        ETag: string;
    };
    pathItems: never;
}
export type Role = components['schemas']['Role'];
export type TicketStatus = components['schemas']['TicketStatus'];
export type TicketPriority = components['schemas']['TicketPriority'];
export type TicketChannel = components['schemas']['TicketChannel'];
export type TicketView = components['schemas']['TicketView'];
export type MessageVisibility = components['schemas']['MessageVisibility'];
export type Organization = components['schemas']['Organization'];
export type Me = components['schemas']['Me'];
export type Member = components['schemas']['Member'];
export type MemberRef = components['schemas']['MemberRef'];
export type Customer = components['schemas']['Customer'];
export type TicketSummary = components['schemas']['TicketSummary'];
export type Ticket = components['schemas']['Ticket'];
export type TicketCreate = components['schemas']['TicketCreate'];
export type TicketPatch = components['schemas']['TicketPatch'];
export type TicketPage = components['schemas']['TicketPage'];
export type CustomerPage = components['schemas']['CustomerPage'];
export type ViewCounts = components['schemas']['ViewCounts'];
export type TicketMetrics = components['schemas']['TicketMetrics'];
export type MessageAuthor = components['schemas']['MessageAuthor'];
export type Message = components['schemas']['Message'];
export type MessageCreate = components['schemas']['MessageCreate'];
export type Activity = components['schemas']['Activity'];
export type TicketCreatedActivity = components['schemas']['TicketCreatedActivity'];
export type StatusChangedActivity = components['schemas']['StatusChangedActivity'];
export type PriorityChangedActivity = components['schemas']['PriorityChangedActivity'];
export type AssigneeChangedActivity = components['schemas']['AssigneeChangedActivity'];
export type Problem = components['schemas']['Problem'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseForbidden = components['responses']['Forbidden'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponsePreconditionFailed = components['responses']['PreconditionFailed'];
export type ResponsePreconditionRequired = components['responses']['PreconditionRequired'];
export type ResponseConflict = components['responses']['Conflict'];
export type ParameterTicketNumber = components['parameters']['TicketNumber'];
export type ParameterPage = components['parameters']['Page'];
export type ParameterSize = components['parameters']['Size'];
export type HeaderETag = components['headers']['ETag'];
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                view?: components["schemas"]["TicketView"];
                status?: components["schemas"]["TicketStatus"][];
                priority?: components["schemas"]["TicketPriority"][];
                /** @description A member id, or `none` for unassigned tickets. */
                assigneeId?: string;
                /**
                 * @description Only tickets of this customer. For customer members it combines with their own scope,
                 *     so another id yields no results.
                 */
                customerId?: string;
                /**
                 * @description Case-insensitive contains match on the subject and the customer name, email and company;
                 *     a number, with or without `#`, matches the ticket number exactly.
                 */
                q?: string;
                /** @description Zero-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /**
                 * @description `field,direction`. `priority` and `status` sort by rank (urgent → low; open → in_progress →
                 *     waiting → resolved), not alphabetically. Ties are broken by `number,desc`.
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tickets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description The created ticket. */
            201: {
                headers: {
                    /** @description URL of the ticket, `/api/tickets/{number}`. */
                    Location?: string;
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTicketMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization-wide metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header: {
                /** @description A single strong validator with the current version, as returned in `ETag`. */
                "If-Match": string;
            };
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TicketPatch"];
            };
        };
        responses: {
            /** @description The updated ticket. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages of the ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description The created message. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                /** @description Searches the name, email and company. */
                q?: string;
                /** @description Zero-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /** @description `field,direction`. Names compare case-insensitively; ties are broken by `id,asc`. */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of customers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignable members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const roleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Role"]> = ["admin", "agent", "customer"];
export const ticketStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketStatus"]> = ["open", "in_progress", "waiting", "resolved"];
export const ticketPriorityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketPriority"]> = ["urgent", "high", "medium", "low"];
export const ticketChannelValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketChannel"]> = ["email", "chat", "phone", "web"];
export const ticketViewValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketView"]> = ["all", "mine", "unassigned", "resolved"];
export const messageVisibilityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MessageVisibility"]> = ["public", "internal"];
export const messageAuthorKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MessageAuthor"]["kind"]> = ["agent", "customer"];
export const ticketCreatedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketCreatedActivity"]["type"]> = ["created"];
export const statusChangedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StatusChangedActivity"]["type"]> = ["status_changed"];
export const priorityChangedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PriorityChangedActivity"]["type"]> = ["priority_changed"];
export const assigneeChangedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AssigneeChangedActivity"]["type"]> = ["assignee_changed"];
