/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, organization and role */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticket inbox
         * @description Agents and admins see every ticket of the organization; customers only see the tickets of
         *     their own customer record. Filters combine with AND; repeated values of one filter combine with OR.
         */
        get: operations["listTickets"];
        put?: never;
        /**
         * Create a ticket
         * @description `customerId` and `assigneeId` must belong to the caller's organization (the assignee must be an
         *     admin or agent). Unknown and foreign ids get the same 400 field error, so other organizations'
         *     data is never revealed.
         */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inbox metrics for the whole organization
         * @description Not affected by inbox filters. Days are computed in the organization time zone.
         */
        get: operations["getTicketMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest activity of the whole organization, newest first (not paginated)
         * @description Staff only. The most recent entries of the activity logs of every ticket of the organization, each with
         *     the number and subject of its ticket. Internal notes are messages, not activity, and never appear.
         */
        get: operations["listRecentActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        /** Ticket detail */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change status, priority and/or assignee
         * @description JSON Merge Patch semantics: absent fields are unchanged and `assigneeId: null` unassigns the
         *     ticket. Requires `If-Match` with the current version. A patch that changes nothing returns 200
         *     without a new version or activity entry. Errors are checked in this order: 401, 403, 404, 428,
         *     400, 412.
         */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/tickets/{number}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        /**
         * Conversation of a ticket, oldest first
         * @description Not paginated. Customers only receive `public` messages. The ticket `description` is part of
         *     the ticket, not the first message.
         */
        get: operations["listMessages"];
        put?: never;
        /** Reply to the customer or add an internal note */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{number}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        /** Activity log of a ticket, newest first (not paginated) */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated customer list and search
         * @description Archived customers are left out unless `archived=true`, which lists only them. The result never
         *     includes customers of other organizations. `openTickets` counts the customer's tickets that are
         *     not `resolved`.
         */
        get: operations["listCustomers"];
        put?: never;
        /**
         * Create a customer
         * @description The email must be unique in the organization, ignoring case and including archived customers; a
         *     duplicate is a 400 field error on `email`.
         */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer metrics for the whole organization
         * @description Computed over the active (non-archived) customers of the organization and not affected by list
         *     filters. `newThisMonth` uses the current month in the organization time zone.
         */
        get: operations["getCustomerMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Distinct company names of the active customers
         * @description Case-insensitive alphabetical order, at most 200 names, without empty values. Names that only differ
         *     in case are listed once. Archived customers do not contribute.
         */
        get: operations["listCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        /**
         * Customer detail
         * @description Archived customers can be read. Foreign and unknown ids both answer 404.
         */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit a customer's contact data and notes
         * @description JSON Merge Patch semantics: absent fields are unchanged and `null` clears `company` and `notes`
         *     (`name` and `email` do not accept `null`). Requires `If-Match` with the current version. A patch that
         *     changes nothing returns 200 without a new version. An archived customer cannot be edited: restore it
         *     first (409). Errors are checked in this order: 401, 403, 404, 428, 400, 412, 409.
         */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/customers/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a customer (admin only)
         * @description Hides the customer from lists, search, metrics and the new-ticket selector; their tickets stay
         *     visible and editable and their portal access stops working. Archiving an archived customer is a 409.
         */
        post: operations["archiveCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an archived customer (admin only)
         * @description Brings the customer back to every list and resumes portal access. Restoring an active customer is a 409.
         */
        post: operations["restoreCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite a customer to the portal (admin only)
         * @description Creates an `invited` `customer` membership bound to the customer's email, creating the user when the
         *     email is new; no email is sent. The person gets access by signing in with that address, which activates
         *     the membership on their first request. A membership of the same customer that was `removed` is invited
         *     again on the same row. The customer must be active: inviting an archived customer is a 409 (restore it
         *     first), and so is a customer that already has an `invited` or `active` access, whose email belongs to a
         *     team member, or whose user is already linked to another customer.
         */
        post: operations["inviteCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Members of the team (admins and agents) with their status and load
         * @description Every admin and agent of the organization in any status, including `removed` ones (clients hide
         *     them by default), ordered by name and then id. Customers with portal access are not part of the team.
         *     `openTickets` counts the unresolved tickets assigned to the member.
         */
        get: operations["listMembers"];
        put?: never;
        /**
         * Invite an admin or agent (admin only)
         * @description Creates an `invited` membership bound to the email, creating the user when the email is new. No email is
         *     sent: the person joins by signing in with that address, which activates the membership on their first
         *     request. Inviting an email that was removed from the team brings the same membership back to `invited`
         *     with the new role. An email that is already an active or invited member, or that belongs to a customer of
         *     the organization, is a 400 on the field `email`.
         */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team metrics for the whole organization
         * @description `staff` counts the active admins and agents. `assignedOpen` and `unassignedOpen` count the unresolved
         *     tickets with and without an assignee. `averageLoad` is `assignedOpen / staff` with one decimal (`0`
         *     without staff). `firstResponseMinutes` is the same median as in the ticket metrics.
         */
        get: operations["getTeamMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the member's user, as `TeamMember.id`. */
                userId: components["parameters"]["MemberUserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the role of an admin or agent (admin only)
         * @description Works on invited and active members. Changing the role of the last active admin is a 409, and so is
         *     changing the role of a removed member. A user that is not an admin or agent of the organization
         *     (unknown, from another organization or a customer) is a 404.
         */
        post: operations["changeMemberRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{userId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the member's user, as `TeamMember.id`. */
                userId: components["parameters"]["MemberUserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a member from the team (admin only)
         * @description Marks the membership `removed`; it is never deleted. The member stops being able to sign in, leaves
         *     `/assignees` and the team metrics, and their unresolved tickets are unassigned in the same transaction,
         *     each with an `assignee_changed` activity whose actor is the caller; resolved tickets keep their assignee.
         *     Removing oneself, the last active admin or an already removed member is a 409. A user that is not an
         *     admin or agent of the organization is a 404.
         */
        post: operations["removeMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members who can be assigned to tickets (admins and agents), by name */
        get: operations["listAssignees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report of the organization over a period, with the previous period of the same length
         * @description Staff only. Everything is computed on the server, per organization, in the organization time zone.
         *     The period covers the last `days` calendar days of the organization, today included: it starts at
         *     00:00 of `today - (days - 1)` and ends now. `previous` figures cover the adjacent period of the same
         *     duration (`[from - (to - from), from)`). Without data the counts are `0` and the medians `null`.
         */
        get: operations["getReportSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "admin" | "agent" | "customer";
        /** @enum {string} */
        TicketStatus: "open" | "in_progress" | "waiting" | "resolved";
        /** @enum {string} */
        TicketPriority: "urgent" | "high" | "medium" | "low";
        /** @enum {string} */
        TicketChannel: "email" | "chat" | "phone" | "web";
        /**
         * @description `all`: every ticket. `mine`: assigned to the caller and not resolved. `unassigned`: without
         *     assignee and not resolved. `resolved`: status `resolved`. Combined with the other filters by AND.
         * @default all
         * @enum {string}
         */
        TicketView: "all" | "mine" | "unassigned" | "resolved";
        /** @enum {string} */
        MessageVisibility: "public" | "internal";
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @example America/Bogota */
            timeZone: string;
        };
        Me: {
            user: components["schemas"]["Member"];
            organization: components["schemas"]["Organization"];
            role: components["schemas"]["Role"];
            /**
             * Format: uuid
             * @description Customer record of a `customer` member; null for admins and agents.
             */
            customerId: string | null;
        };
        /** @description An admin or agent of the organization. */
        Member: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description A member as shown inside other resources, without contact data. */
        MemberRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /**
         * @description `invited`: bound to an email that has not signed in yet. `active`: can use the API. `removed`: can no
         *     longer sign in; the membership is kept for the history that references it.
         * @enum {string}
         */
        MemberStatus: "invited" | "active" | "removed";
        /**
         * @description A member of the organization with their membership status: an admin or agent in the team routes, or the
         *     invited portal member (`role` `customer`) returned by `inviteCustomer`.
         */
        TeamMember: {
            /**
             * Format: uuid
             * @description Id of the member's user.
             */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["MemberStatus"];
            /** @description Unresolved tickets assigned to the member. */
            openTickets: number;
            /**
             * Format: date-time
             * @description When the membership became active; null while it is `invited`.
             */
            joinedAt: string | null;
            /**
             * Format: date-time
             * @description When the current invitation was made; null for members that never were invited.
             */
            invitedAt: string | null;
        };
        MemberInvite: {
            /** Format: email */
            email: string;
            /** @description Defaults to the part of the email before the `@`. Ignored when the user already exists. */
            name?: string;
            /** @enum {string} */
            role: "admin" | "agent";
        };
        MemberRoleChange: {
            /** @enum {string} */
            role: "admin" | "agent";
        };
        TeamMetrics: {
            /** @description Active admins and agents. */
            staff: number;
            /** @description Unresolved tickets with an assignee. */
            assignedOpen: number;
            /** @description Unresolved tickets without an assignee. */
            unassignedOpen: number;
            /** @description `assignedOpen / staff` with one decimal; `0` without staff. */
            averageLoad: number;
            /** @description Same median as `TicketMetrics.firstResponseMinutes`; null without data. */
            firstResponseMinutes: number | null;
            firstResponseTargetMinutes: number;
        };
        Customer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            company: string | null;
        };
        /** @description A customer in lists, with its ticket counts. `Customer` is the reference embedded in tickets. */
        CustomerSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            company: string | null;
            /** @description Tickets of the customer whose status is not `resolved`. */
            openTickets: number;
            totalTickets: number;
            /** Format: date-time */
            createdAt: string;
            archived: boolean;
        };
        /**
         * @description A customer with its profile: every field of CustomerSummary plus `notes`, `archivedAt`, `version` and
         *     `portalAccess`. It is written out in full instead of composing CustomerSummary with `allOf`, because
         *     `additionalProperties: false` on each `allOf` branch makes a JSON Schema validator reject the fields of
         *     the other branch.
         */
        CustomerDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            company: string | null;
            /** @description Tickets of the customer whose status is not `resolved`. */
            openTickets: number;
            totalTickets: number;
            /** Format: date-time */
            createdAt: string;
            archived: boolean;
            notes: string | null;
            /** Format: date-time */
            archivedAt: string | null;
            /** Format: int64 */
            version: number;
            /**
             * @description Follows the status of the customer's membership: `none` without a membership or when it was removed,
             *     `invited` until the person first signs in, `active` afterwards. It does not account for archiving:
             *     while `archived` is `true` the portal access is suspended (the member gets 401) whatever
             *     `portalAccess` says. Clients should treat an archived customer as suspended.
             * @enum {string}
             */
            portalAccess: "none" | "invited" | "active";
        };
        CustomerCreate: {
            name: string;
            /** Format: email */
            email: string;
            company?: string | null;
            notes?: string | null;
        };
        /** @description Same fields as CustomerCreate, all optional. `name` and `email` do not accept `null`. */
        CustomerPatch: {
            name?: string;
            /** Format: email */
            email?: string;
            company?: string | null;
            notes?: string | null;
        };
        /** @description Counts over the active (non-archived) customers of the organization. */
        CustomerMetrics: {
            total: number;
            /** @description Distinct non-empty company names, ignoring case. */
            companies: number;
            /** @description Customers with at least one ticket that is not `resolved`. */
            withOpenTickets: number;
            /** @description Customers created in the current month of the organization time zone. */
            newThisMonth: number;
        };
        TicketSummary: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            number: number;
            subject: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            channel: components["schemas"]["TicketChannel"];
            customer: components["schemas"]["Customer"];
            assignee: components["schemas"]["MemberRef"] | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Last activity, either a field change or a public message.
             */
            updatedAt: string;
        };
        /** @description Ticket detail. Same fields as TicketSummary plus `description` and `version`. */
        Ticket: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            number: number;
            subject: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            channel: components["schemas"]["TicketChannel"];
            customer: components["schemas"]["Customer"];
            assignee: components["schemas"]["MemberRef"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            description: string;
            /** Format: int64 */
            version: number;
        };
        TicketCreate: {
            /** Format: uuid */
            customerId: string;
            subject: string;
            description: string;
            /** @default medium */
            priority?: components["schemas"]["TicketPriority"];
            /** @default web */
            channel?: components["schemas"]["TicketChannel"];
            /** Format: uuid */
            assigneeId?: string | null;
        };
        TicketPatch: {
            status?: components["schemas"]["TicketStatus"];
            priority?: components["schemas"]["TicketPriority"];
            /**
             * Format: uuid
             * @description `null` unassigns the ticket.
             */
            assigneeId?: string | null;
        };
        /** @description An empty page past the last one is valid (200 with no items); `totalPages` is 0 when there are no items. */
        TicketPage: {
            items: components["schemas"]["TicketSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        /** @description An empty page past the last one is valid (200 with no items); `totalPages` is 0 when there are no items. */
        CustomerPage: {
            items: components["schemas"]["CustomerSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        ViewCounts: {
            all: number;
            mine: number;
            unassigned: number;
            resolved: number;
        };
        TicketMetrics: {
            open: number;
            /** @description Tickets created today (organization time zone) that are still open. */
            openedToday: number;
            inProgress: number;
            inProgressAssignedToMe: number;
            /** @description Distinct tickets that entered `resolved` today, from the activity log. */
            resolvedToday: number;
            resolvedYesterday: number;
            /**
             * @description Median minutes, rounded to the nearest integer, from creation to the first public agent
             *     message, over tickets created in the last 168 hours that have one; null when there are none.
             */
            firstResponseMinutes: number | null;
            firstResponseTargetMinutes: number;
            views: components["schemas"]["ViewCounts"];
        };
        MessageAuthor: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "agent" | "customer";
        };
        Message: {
            /** Format: uuid */
            id: string;
            body: string;
            visibility: components["schemas"]["MessageVisibility"];
            author: components["schemas"]["MessageAuthor"];
            /** Format: date-time */
            createdAt: string;
        };
        MessageCreate: {
            body: string;
            visibility: components["schemas"]["MessageVisibility"];
        };
        Activity: components["schemas"]["TicketCreatedActivity"] | components["schemas"]["StatusChangedActivity"] | components["schemas"]["PriorityChangedActivity"] | components["schemas"]["AssigneeChangedActivity"];
        TicketCreatedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "created";
            actor: components["schemas"]["MemberRef"];
            /** Format: date-time */
            createdAt: string;
        };
        StatusChangedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "status_changed";
            actor: components["schemas"]["MemberRef"];
            from: components["schemas"]["TicketStatus"];
            to: components["schemas"]["TicketStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        PriorityChangedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "priority_changed";
            actor: components["schemas"]["MemberRef"];
            from: components["schemas"]["TicketPriority"];
            to: components["schemas"]["TicketPriority"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description `from` and `to` keep the member id and the name at the time of the change; null means unassigned. */
        AssigneeChangedActivity: {
            /** Format: uuid */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assignee_changed";
            actor: components["schemas"]["MemberRef"];
            from: components["schemas"]["MemberRef"] | null;
            to: components["schemas"]["MemberRef"] | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description An activity entry of the organization together with the ticket it belongs to.
         * @example {
         *       "ticketNumber": 1048,
         *       "subject": "No puedo acceder a mi cuenta",
         *       "activity": {
         *         "id": "4a7c1c52-3f6e-4a58-9d0b-2b2f7f9a6c10",
         *         "type": "status_changed",
         *         "actor": {
         *           "id": "3f0c2f9a-6a56-4d1f-9c3e-1f4b0a7d2c11",
         *           "name": "Laura Méndez"
         *         },
         *         "from": "open",
         *         "to": "in_progress",
         *         "createdAt": "2026-10-04T14:52:00Z"
         *       }
         *     }
         */
        ActivityFeedItem: {
            /**
             * Format: int64
             * @example 1048
             */
            ticketNumber: number;
            /** @example No puedo acceder a mi cuenta */
            subject: string;
            activity: components["schemas"]["Activity"];
        };
        /**
         * @example {
         *       "period": {
         *         "from": "2026-09-28T05:00:00Z",
         *         "to": "2026-10-04T15:00:00Z",
         *         "days": 7,
         *         "timeZone": "America/Bogota"
         *       },
         *       "created": {
         *         "value": 42,
         *         "previous": 38
         *       },
         *       "resolved": {
         *         "value": 35,
         *         "previous": 31
         *       },
         *       "firstResponseMinutes": {
         *         "value": 18,
         *         "previous": 22,
         *         "target": 30
         *       },
         *       "resolutionHours": {
         *         "value": 6.5,
         *         "previous": null
         *       },
         *       "byDay": [
         *         {
         *           "date": "2026-09-28",
         *           "created": 6,
         *           "resolved": 5
         *         }
         *       ],
         *       "byChannel": [
         *         {
         *           "channel": "email",
         *           "created": 30,
         *           "share": 71.4
         *         },
         *         {
         *           "channel": "chat",
         *           "created": 12,
         *           "share": 28.6
         *         }
         *       ],
         *       "byAgent": [
         *         {
         *           "member": {
         *             "id": "3f0c2f9a-6a56-4d1f-9c3e-1f4b0a7d2c11",
         *             "name": "Laura Méndez"
         *           },
         *           "status": "active",
         *           "resolved": 20,
         *           "firstResponseMinutes": 15,
         *           "openAssigned": 4
         *         }
         *       ]
         *     }
         */
        ReportSummary: {
            period: components["schemas"]["ReportRange"];
            created: components["schemas"]["ReportCount"];
            resolved: components["schemas"]["ReportCount"];
            firstResponseMinutes: components["schemas"]["ReportFirstResponse"];
            resolutionHours: components["schemas"]["ReportResolution"];
            /** @description One entry per calendar day of the period, oldest first; days without data are `0`. */
            byDay: components["schemas"]["ReportDay"][];
            /**
             * @description Channels with at least one ticket created in the period, largest first (ties by channel name);
             *     empty without data. The `share` values add up to exactly `100`.
             */
            byChannel: components["schemas"]["ReportChannel"][];
            /**
             * @description Every active admin and agent, plus the members who are no longer active (removed, or invited again)
             *     and resolved tickets or gave a first response in the period, most resolved first (ties by name, then
             *     id). `status` tells them apart.
             */
            byAgent: components["schemas"]["ReportAgent"][];
        };
        /**
         * @description The window the report covers. `from` is the start of the first day in the organization time zone and
         *     `to` is the moment of the request.
         */
        ReportRange: {
            /**
             * Format: date-time
             * @example 2026-09-28T05:00:00Z
             */
            from: string;
            /**
             * Format: date-time
             * @example 2026-10-04T15:00:00Z
             */
            to: string;
            /**
             * @example 7
             * @enum {integer}
             */
            days: 7 | 30 | 90;
            /** @example America/Bogota */
            timeZone: string;
        };
        ReportCount: {
            /**
             * @description Count in the period.
             * @example 42
             */
            value: number;
            /**
             * @description Count in the previous period of the same duration.
             * @example 38
             */
            previous: number;
        };
        /**
         * @description Median minutes, rounded to the nearest integer, from creation to the first public agent message, over
         *     the tickets created in the period that have one; `null` when there are none.
         */
        ReportFirstResponse: {
            /** @example 18 */
            value: number | null;
            /** @example 22 */
            previous: number | null;
            /**
             * @description Organization target, in minutes.
             * @example 30
             */
            target: number;
        };
        /**
         * @description Median hours, with one decimal, from creation to the first time a ticket entered `resolved`, over the
         *     tickets created in the period that were resolved; `null` when there are none.
         */
        ReportResolution: {
            /** @example 6.5 */
            value: number | null;
            /** @example null */
            previous: number | null;
        };
        ReportDay: {
            /**
             * Format: date
             * @description Calendar day in the organization time zone.
             * @example 2026-09-28
             */
            date: string;
            /**
             * @description Tickets created that day.
             * @example 6
             */
            created: number;
            /**
             * @description Distinct tickets that entered `resolved` that day. A ticket resolved, reopened and resolved again on
             *     different days counts on each of them, so the days can add up to more than `resolved.value`.
             * @example 5
             */
            resolved: number;
        };
        ReportChannel: {
            channel: components["schemas"]["TicketChannel"];
            /**
             * @description Tickets created in the period through this channel.
             * @example 30
             */
            created: number;
            /**
             * @description Percentage of the tickets created in the period, one decimal.
             * @example 71.4
             */
            share: number;
        };
        ReportAgent: {
            member: components["schemas"]["MemberRef"];
            /** @description Membership status. Anything other than `active` is someone who left but worked in the period. */
            status: components["schemas"]["MemberStatus"];
            /**
             * @description Distinct tickets this member moved to `resolved` in the period (the actor of the activity).
             * @example 20
             */
            resolved: number;
            /**
             * @description Median first response of the tickets created in the period whose first public message is theirs;
             *     `null` without data.
             * @example 15
             */
            firstResponseMinutes: number | null;
            /**
             * @description Tickets assigned to this member that are not `resolved`, as of now.
             * @example 4
             */
            openAssigned: number;
        };
        /** @description RFC 9457 Problem Details. An absent `type` means `about:blank`, as the RFC defines. */
        Problem: {
            /** @default about:blank */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Field errors of a validation failure. */
            errors?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Malformed request, invalid parameter or validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No authenticated principal. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The role does not allow the action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found in the caller's scope. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource changed since the client read it. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The update did not send `If-Match`. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The action is not allowed in the current state of the resource (for example archiving twice). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TicketNumber: number;
        CustomerId: string;
        /** @description Id of the member's user, as `TeamMember.id`. */
        MemberUserId: string;
        /** @description Zero-based page index. */
        Page: number;
        Size: number;
        /** @description Number of entries to return. */
        ActivityFeedSize: number;
        /** @description Length of the report period, in calendar days of the organization time zone. */
        ReportPeriod: "7d" | "30d" | "90d";
    };
    requestBodies: never;
    headers: {
        /** @description Current version of the resource, quoted, for `If-Match`. */
        ETag: string;
    };
    pathItems: never;
}
export type Role = components['schemas']['Role'];
export type TicketStatus = components['schemas']['TicketStatus'];
export type TicketPriority = components['schemas']['TicketPriority'];
export type TicketChannel = components['schemas']['TicketChannel'];
export type TicketView = components['schemas']['TicketView'];
export type MessageVisibility = components['schemas']['MessageVisibility'];
export type Organization = components['schemas']['Organization'];
export type Me = components['schemas']['Me'];
export type Member = components['schemas']['Member'];
export type MemberRef = components['schemas']['MemberRef'];
export type MemberStatus = components['schemas']['MemberStatus'];
export type TeamMember = components['schemas']['TeamMember'];
export type MemberInvite = components['schemas']['MemberInvite'];
export type MemberRoleChange = components['schemas']['MemberRoleChange'];
export type TeamMetrics = components['schemas']['TeamMetrics'];
export type Customer = components['schemas']['Customer'];
export type CustomerSummary = components['schemas']['CustomerSummary'];
export type CustomerDetail = components['schemas']['CustomerDetail'];
export type CustomerCreate = components['schemas']['CustomerCreate'];
export type CustomerPatch = components['schemas']['CustomerPatch'];
export type CustomerMetrics = components['schemas']['CustomerMetrics'];
export type TicketSummary = components['schemas']['TicketSummary'];
export type Ticket = components['schemas']['Ticket'];
export type TicketCreate = components['schemas']['TicketCreate'];
export type TicketPatch = components['schemas']['TicketPatch'];
export type TicketPage = components['schemas']['TicketPage'];
export type CustomerPage = components['schemas']['CustomerPage'];
export type ViewCounts = components['schemas']['ViewCounts'];
export type TicketMetrics = components['schemas']['TicketMetrics'];
export type MessageAuthor = components['schemas']['MessageAuthor'];
export type Message = components['schemas']['Message'];
export type MessageCreate = components['schemas']['MessageCreate'];
export type Activity = components['schemas']['Activity'];
export type TicketCreatedActivity = components['schemas']['TicketCreatedActivity'];
export type StatusChangedActivity = components['schemas']['StatusChangedActivity'];
export type PriorityChangedActivity = components['schemas']['PriorityChangedActivity'];
export type AssigneeChangedActivity = components['schemas']['AssigneeChangedActivity'];
export type ActivityFeedItem = components['schemas']['ActivityFeedItem'];
export type ReportSummary = components['schemas']['ReportSummary'];
export type ReportRange = components['schemas']['ReportRange'];
export type ReportCount = components['schemas']['ReportCount'];
export type ReportFirstResponse = components['schemas']['ReportFirstResponse'];
export type ReportResolution = components['schemas']['ReportResolution'];
export type ReportDay = components['schemas']['ReportDay'];
export type ReportChannel = components['schemas']['ReportChannel'];
export type ReportAgent = components['schemas']['ReportAgent'];
export type Problem = components['schemas']['Problem'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseForbidden = components['responses']['Forbidden'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponsePreconditionFailed = components['responses']['PreconditionFailed'];
export type ResponsePreconditionRequired = components['responses']['PreconditionRequired'];
export type ResponseConflict = components['responses']['Conflict'];
export type ParameterTicketNumber = components['parameters']['TicketNumber'];
export type ParameterCustomerId = components['parameters']['CustomerId'];
export type ParameterMemberUserId = components['parameters']['MemberUserId'];
export type ParameterPage = components['parameters']['Page'];
export type ParameterSize = components['parameters']['Size'];
export type ParameterActivityFeedSize = components['parameters']['ActivityFeedSize'];
export type ParameterReportPeriod = components['parameters']['ReportPeriod'];
export type HeaderETag = components['headers']['ETag'];
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                view?: components["schemas"]["TicketView"];
                status?: components["schemas"]["TicketStatus"][];
                priority?: components["schemas"]["TicketPriority"][];
                /** @description A member id, or `none` for unassigned tickets. */
                assigneeId?: string;
                /**
                 * @description Only tickets of this customer. For customer members it combines with their own scope,
                 *     so another id yields no results.
                 */
                customerId?: string;
                /**
                 * @description Case-insensitive contains match on the subject and the customer name, email and company;
                 *     a number, with or without `#`, matches the ticket number exactly.
                 */
                q?: string;
                /** @description Zero-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /**
                 * @description `field,direction`. `priority` and `status` sort by rank (urgent → low; open → in_progress →
                 *     waiting → resolved), not alphabetically. Ties are broken by `number,desc`.
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tickets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description The created ticket. */
            201: {
                headers: {
                    /** @description URL of the ticket, `/api/tickets/{number}`. */
                    Location?: string;
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTicketMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization-wide metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRecentActivity: {
        parameters: {
            query?: {
                /** @description Number of entries to return. */
                size?: components["parameters"]["ActivityFeedSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityFeedItem"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header: {
                /** @description A single strong validator with the current version, as returned in `ETag`. */
                "If-Match": string;
            };
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TicketPatch"];
            };
        };
        responses: {
            /** @description The updated ticket. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["PreconditionFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages of the ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description The created message. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: components["parameters"]["TicketNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                /** @description Searches the name, email and company. */
                q?: string;
                /** @description Exact company name, compared case-insensitively. An unknown company gives an empty page. */
                company?: string;
                /** @description `false` (default) lists active customers; `true` lists only archived ones. */
                archived?: boolean;
                /** @description Zero-based page index. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                /**
                 * @description `field,direction` with `name`, `createdAt` or `openTickets`. Names compare case-insensitively;
                 *     ties are broken by `id,asc`.
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of customers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description The created customer. */
            201: {
                headers: {
                    /** @description URL of the customer, `/api/customers/{id}`. */
                    Location?: string;
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCustomerMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization-wide customer metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company names. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header: {
                /** @description A single strong validator with the current version, as returned in `ETag`. */
                "If-Match": string;
            };
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["CustomerPatch"];
            };
        };
        responses: {
            /** @description The updated customer. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    archiveCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived customer. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    restoreCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored customer. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    inviteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invited portal member (`role` is `customer`). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "sofia.rios@acme.example",
                 *       "name": "Sofía Ríos",
                 *       "role": "agent"
                 *     }
                 */
                "application/json": components["schemas"]["MemberInvite"];
            };
        };
        responses: {
            /** @description The invited member. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTeamMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization-wide team metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    changeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the member's user, as `TeamMember.id`. */
                userId: components["parameters"]["MemberUserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "role": "admin"
                 *     }
                 */
                "application/json": components["schemas"]["MemberRoleChange"];
            };
        };
        responses: {
            /** @description The member with their new role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the member's user, as `TeamMember.id`. */
                userId: components["parameters"]["MemberUserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The removed member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAssignees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignable members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getReportSummary: {
        parameters: {
            query?: {
                /** @description Length of the report period, in calendar days of the organization time zone. */
                period?: components["parameters"]["ReportPeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const roleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Role"]> = ["admin", "agent", "customer"];
export const ticketStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketStatus"]> = ["open", "in_progress", "waiting", "resolved"];
export const ticketPriorityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketPriority"]> = ["urgent", "high", "medium", "low"];
export const ticketChannelValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketChannel"]> = ["email", "chat", "phone", "web"];
export const ticketViewValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketView"]> = ["all", "mine", "unassigned", "resolved"];
export const messageVisibilityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MessageVisibility"]> = ["public", "internal"];
export const memberStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MemberStatus"]> = ["invited", "active", "removed"];
export const memberInviteRoleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MemberInvite"]["role"]> = ["admin", "agent"];
export const memberRoleChangeRoleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MemberRoleChange"]["role"]> = ["admin", "agent"];
export const customerDetailPortalAccessValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CustomerDetail"]["portalAccess"]> = ["none", "invited", "active"];
export const messageAuthorKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MessageAuthor"]["kind"]> = ["agent", "customer"];
export const ticketCreatedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TicketCreatedActivity"]["type"]> = ["created"];
export const statusChangedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StatusChangedActivity"]["type"]> = ["status_changed"];
export const priorityChangedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PriorityChangedActivity"]["type"]> = ["priority_changed"];
export const assigneeChangedActivityTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AssigneeChangedActivity"]["type"]> = ["assignee_changed"];
export const reportRangeDaysValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ReportRange"]["days"]> = [7, 30, 90];
export const componentsParametersReportPeriodValues: ReadonlyArray<FlattenedDeepRequired<components>["parameters"]["ReportPeriod"]> = ["7d", "30d", "90d"];
